version: '3.1'

services:
  postgresdb:
    image: postgres
    environment:
      POSTGRES_DB: student-enrolment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
